### ISSUE TITLE
無法打出 `暫停`

### ISSUE THREAD

**Issue by JustSimplyKyle** [rime/rime-combo-pinyin#9]
展廳
![image](https://user-images.githubusercontent.com/68589851/218766797-d7da5998-fc19-4a2b-b1c0-bac9943f7569.png)
任何與暫相關之詞語皆無法打出

**Comment by LEOYoon-Tsaw** [comment]
試試zan/zham/zam

**Comment by JustSimplyKyle** [comment]
zan 可使用，不過已經使用下列轉換
```yaml
  zh_tw:
    option_name: zh_tw
    opencc_config: t2tw.json
```
